import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'idiom'
})
export class IdiomPipe implements PipeTransform {

  transform(value: unknown, ...args: unknown[]): unknown {
    const languageMap: { [key: string]: string } = {
      'ja': 'Japonés',
      'en': 'Inglés',
      'es': 'Español',
      'fr': 'Francés',
      'de': 'Alemán',
      'it': 'Italiano',
      'pt': 'Portugués',
      'ru': 'Ruso',
      'zh': 'Chino',
      'ko': 'Coreano',
      'ar': 'Árabe',
      'hi': 'Hindi',
      'nl': 'Neerlandés',
      'sv': 'Sueco',
      'no': 'Noruego',
      'fi': 'Finlandés',
      'da': 'Danés',
      'pl': 'Polaco',
      'tr': 'Turco',
      'el': 'Griego',
      'he': 'Hebreo',
      'th': 'Tailandés',
      'vi': 'Vietnamita',
      'id': 'Indonesio',
      'ms': 'Malayo',
      'tl': 'Tagalo',
      'uk': 'Ucraniano',
      'hu': 'Húngaro',
      'cs': 'Checo',
      'ro': 'Rumano',
      'bg': 'Búlgaro',
      'hr': 'Croata',
      'sk': 'Eslovaco',
      'sl': 'Esloveno',
      'lt': 'Lituano',
      'lv': 'Letón',
      'et': 'Estonio',
      'is': 'Islandés',
      'mt': 'Maltés',
      'cy': 'Galés',
      'ie': 'Irlandés',
      'za': 'Afrikáans',
      'eg': 'Árabe Egipcio',
      'ma': 'Árabe Marroquí',
      'dz': 'Árabe Argelino',
      'tn': 'Árabe Tunecino',
      'ng': 'Inglés Nigeriano',
      'ke': 'Inglés Keniano',
      'gh': 'Inglés Ghanés',
      'sn': 'Francés Senegalés',
      'ci': 'Francés Marfileño',
      'cm': 'Francés Camerunés',
      'ug': 'Inglés Ugandés',
      'tz': 'Swahili',
      'zm': 'Inglés Zambiano',
      'zw': 'Inglés Zimbabuense',
      'mz': 'Portugués Mozambicano',
      'ao': 'Portugués Angoleño',
      'na': 'Inglés Namibio',
      'bw': 'Inglés Botsuano',
      'sz': 'Inglés Suazi',
      'ls': 'Inglés Lesotense',
      'mw': 'Inglés Malauí',
      'mg': 'Malgache',
      'mu': 'Inglés Mauriciano',
      'sc': 'Inglés Seychellense',
      'cv': 'Portugués Caboverdiano',
      'gw': 'Portugués Guineano',
      'gq': 'Español Ecuatoguineano',
      'ga': 'Francés Gabonés',
      'cg': 'Francés Congoleño',
      'cd': 'Francés Congoleño',
      'st': 'Portugués Santotomense',
      'bj': 'Francés Beninés',
      'bf': 'Francés Burkinés',
      'ml': 'Francés Maliense',
      'ne': 'Francés Nigerino',
      'td': 'Francés Chadiano',
      'mr': 'Árabe Mauritano',
      'gm': 'Inglés Gambiano',
      'lr': 'Inglés Liberiano',
      'so': 'Somalí',
      'dj': 'Francés Yibutiano',
      'er': 'Tigriña',
      'sd': 'Árabe Sudanés',
      'ss': 'Inglés Sudanés del Sur',
      'cf': 'Francés Centroafricano',
      'rw': 'Kinyarwanda',
      'bi': 'Kirundi',
      'km': 'Comorense',
      'yt': 'Francés Mahorense',
      're': 'Francés Reunionés',
      'tf': 'Francés',
      'pm': 'Francés',
      'gl': 'Groenlandés',
      'fo': 'Feroés',
      'ax': 'Sueco',
      'sj': 'Noruego',
      'bv': 'Noruego',
      'hm': 'Inglés',
      'io': 'Inglés',
      'aq': 'Inglés',
      'gs': 'Inglés',
      'pn': 'Inglés',
      'tk': 'Tokelauano',
      'nu': 'Niueano',
      'ck': 'Maorí',
      'ws': 'Samoano',
      'as': 'Inglés Samoano',
      'to': 'Tongano',
      'tv': 'Tuvaluano',
      'fm': 'Inglés Micronesio',
      'mh': 'Inglés Marshallés',
      'pw': 'Inglés Palauano',
      'nr': 'Nauruano',
      'ki': 'Inglés Kiribatiano',
      'pg': 'Tok Pisin',
      'sb': 'Inglés Salomonense',
      'vu': 'Bislama',
      'nc': 'Francés Neocaledonio',
      'pf': 'Francés Polinesio',
      'wf': 'Francés Wallisiano',
      'fj': 'Inglés Fiyiano'
    };

    return languageMap[value as string] || 'Idioma desconocido';
  }

}
